"""
components/chatbot.py
Sidebar chatbot that answers questions using pre‑generated supply chain insights.
"""

import json
import os
import streamlit as st
from agent import chat_with_data

# Path to insights JSON (generated by insights/generate_insights.py)
INSIGHTS_PATH = os.path.join(
    os.path.dirname(os.path.dirname(__file__)),
    "insights",
    "supply_chain_insights.json"
)

@st.cache_resource
def load_insights():
    """Load the supply chain knowledge base JSON once."""
    try:
        with open(INSIGHTS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except FileNotFoundError:
        return None

def render_chatbot():
    """Render the chatbot UI in the sidebar."""
    insights = load_insights()
    if not insights:
        st.warning("⚠️ Insights file not found. Run `python insights/generate_insights.py` first.")
        return

    st.markdown("---")
    st.markdown("### 💬 Ask ARIA")

    # Chat history
    if "chat_messages" not in st.session_state:
        st.session_state.chat_messages = []

    # Display previous messages
    for msg in st.session_state.chat_messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    # Input box
    if prompt := st.chat_input("Ask about stock, risks, BOM, suppliers…"):
        # Add user message
        st.session_state.chat_messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        # Generate answer
        with st.chat_message("assistant"):
            with st.spinner("Thinking…"):
                answer = get_answer(prompt, insights)
            st.markdown(answer)

        st.session_state.chat_messages.append({"role": "assistant", "content": answer})

def get_answer(question: str, insights: dict) -> str:
    """
    Answer a question using the insights JSON.
    If Azure client is available, use LLM with the full markdown context.
    Otherwise fall back to a simple keyword matcher.
    """
    # Use LLM if Azure is configured
    if st.session_state.azure_client:
        full_knowledge = insights.get("full_markdown", "")
        if len(full_knowledge) > 12000:
            full_knowledge = full_knowledge[:12000] + "\n… (truncated)"

        context = f"""
You are ARIA, a supply chain intelligence assistant for Revvity FI11 Turku.
Answer the user's question based **only** on the following knowledge base.
Do not invent facts. If the answer is not in the knowledge base, say so clearly.

KNOWLEDGE BASE:
{full_knowledge}

USER QUESTION: {question}
"""
        try:
            response = chat_with_data(
                st.session_state.azure_client,
                st.session_state.get("deployment_name", "gpt-4o-mini"),
                question,
                context
            )
            return response
        except Exception as e:
            return f"⚠️ LLM error: {e}. Falling back to manual search."

    # Fallback: simple keyword matching
    return manual_answer(question, insights)

def manual_answer(question: str, insights: dict) -> str:
    """Very basic keyword‑based fallback when no Azure client is available."""
    q = question.lower()
    snap = insights.get("plant_snapshot", {})
    critical = insights.get("critical_materials", [])
    healthy = insights.get("healthy_materials", [])
    replenish = insights.get("replenishment_actions", [])
    risks = insights.get("executive_risks", [])

    if "critical" in q or "urgent" in q:
        if critical:
            names = ", ".join(m["name"] for m in critical)
            return f"⚠️ Critical materials: {names}. Immediate action required for {critical[0]['name']} (order {critical[0]['order_quantity_required']} units)."
        else:
            return "No critical materials at this time."
    elif "healthy" in q or "safe" in q:
        if healthy:
            names = ", ".join(m["name"] for m in healthy[:3])
            return f"✅ Healthy materials: {names}. Stock levels are comfortable."
        else:
            return "No healthy materials reported."
    elif "replenish" in q or "order" in q:
        if replenish:
            r = replenish[0]
            return f"📦 Immediate order: {r['order_qty']} units of {r['name']}. Formula: {r['formula']}."
        else:
            return "No replenishment orders required at this time."
    elif "risk" in q:
        if risks:
            return "Key risks:\n" + "\n".join(f"- {r}" for r in risks[:2])
        else:
            return "No systemic risks identified."
    elif "supplier" in q:
        consol = insights.get("supplier_consolidation", [])
        if consol:
            top = consol[0]
            return f"Top consolidation opportunity: {top['supplier']} supplies {len(top['materials'])} materials including {', '.join(top['materials'][:3])}."
        else:
            return "No supplier consolidation data available."
    else:
        return ("I can answer questions about critical/healthy materials, replenishment orders, risks, and suppliers. "
                "Please try a more specific question (or configure your Azure API key for full intelligence).")
